In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
# standard lib
import os, pwd, sys, json, yaml, atexit, tempfile, inspect
from pathlib import Path

# for data-science
import pandas as pd, numpy as np, quadfeather
from pyarrow import feather

# for plotting
import matplotlib as mpl, matplotlib.pyplot as plt, seaborn as sns

# for cellular-data
import scprep, anndata as ad

In [3]:
from featherplot.utils import MockSingleCellData, AnnDataProcessor, QuadFeatherRenamer
from featherplot.utils import SeriesToChannel

from featherplot.utils import collapse_user
from featherplot.deepscatter import Tileset

In [4]:
mocker = MockSingleCellData()
adata = mocker.adata

In [5]:
adata

AnnData object with n_obs × n_vars = 1000 × 100
    obs: 'barcodes', 'conditions'
    var: 'is_hvg'
    obsm: 'X_mock'
    layers: 'X_norm'

### Create Processor
> this will help us extract the embedding layer and the gene expression layer

In [6]:
pipe = AnnDataProcessor(adata, 'X_mock', 'X_norm')

#### sidecars

Deepscatter calls additional columns `sidecars`, in our case those are the columns of gene expression. We place these values in `df_s`.

In [9]:
df_s = pipe.get_sidecars()
df_s.head()

gene_symbols,gene_symbol 0,gene_symbol 1,gene_symbol 2,gene_symbol 3,gene_symbol 4,gene_symbol 5,gene_symbol 6,gene_symbol 7,gene_symbol 8,gene_symbol 9,...,gene_symbol 90,gene_symbol 91,gene_symbol 92,gene_symbol 93,gene_symbol 94,gene_symbol 95,gene_symbol 96,gene_symbol 97,gene_symbol 98,gene_symbol 99
barcodes,,,,,,,,,,,,,,,,,,,,,
barcode 0,0.803276,0.244524,-0.192386,-0.800793,-2.016473,0.821837,-0.298254,1.246355,0.357815,-0.528874,...,-1.088258,-2.642169,-0.956667,0.238179,-2.116511,-1.038880,0.282109,-1.040906,0.348024,0.703587
barcode 1,0.656503,-2.400139,1.251113,0.512456,0.306186,1.588643,-0.882513,0.265882,-1.937371,-0.279166,...,-0.395451,1.474536,0.433047,0.067309,1.097640,0.249324,0.538526,0.000884,2.739368,-1.101643
barcode 2,0.014030,1.228871,1.006785,0.720465,-0.121492,0.115829,0.695498,-0.896377,-0.402044,-1.376581,...,-0.416621,-0.667497,0.169813,0.311218,1.030311,0.396096,-0.754883,1.440937,0.849603,-0.541365
barcode 3,1.219619,0.834831,0.163721,0.343506,-0.164225,-0.095177,-1.137599,1.097777,-0.663735,0.797283,...,-1.010034,1.370871,-0.276237,-0.864229,-0.338752,0.555502,-1.301947,0.400086,0.205288,-1.246912
barcode 4,-0.355697,-0.515200,-1.566528,0.548676,0.168378,-1.152343,-0.225759,1.476776,-0.589473,0.030619,...,0.351259,0.823491,-0.408399,0.725561,-0.438170,-0.834018,-0.025542,1.571137,1.902323,-0.986374

In [ ]:
import pandas as pd


df = pd.read_csv(filepath_or_buffer="sample.csv")

import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel

 
tokenizer = AutoTokenizer.from_pretrained("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)
model = AutoModel.from_pretrained("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)
 
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0]
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

 
texts = df["COMPLAINT_SUMMARY"].astype(str).tolist()

encoded_input = tokenizer(texts, padding=True, truncation=True, max_length=8192, return_tensors='pt')

 
with torch.no_grad():
    model_output = model(**encoded_input)
    
 
embeddings = mean_pooling(model_output, encoded_input["attention_mask"])
 
embeddings = F.normalize(embeddings, p=2, dim=1)
 
embeddings_hd = embeddings.cpu().numpy()
print("High-dimensional embeddings shape:", embeddings_hd.shape)
from sklearn.manifold import TSNE # change dimension reduction using UMAP

tsne = TSNE(n_components=2, random_state=42, perplexity=2, n_iter=1000)
embeddings_2d = tsne.fit_transform(embeddings_hd)
print("2D embeddings shape:", embeddings_2d.shape)

df["x"] = embeddings_2d[:, 0]
df["y"] = embeddings_2d[:, 1]
df["z"] = embeddings_2d[:, 2]

 
metadata_fields = [
    "COMPLAINT_ID", "CATEGORY", "SUBCATEGORY", "UPDATED_DATE", "STATE"
]

# Create df_q with selected fields + coordinates
df_q = df[metadata_fields].copy()
df_q["x"] = df["x"]
df_q["y"] = df["y"]
# df_q["z"] = df["z"]

# Convert categorical columns to strings (important for tiling)
df_q = df_q.astype(str)

# Save to quadfeather-compatible format
df_q.to_parquet("df_q.parquet")  # This is an alternative to quadfeather format

<All keys matched successfully>

High-dimensional embeddings shape: (60, 768)

/home/hm3/Desktop/complaint-plotter/.venv/lib/python3.13/site-packages/sklearn/manifold/_t_sne.py:1164: FutureWarning: 'n_iter' was renamed to 'max_iter' in version 1.5 and will be removed in 1.7.
  warnings.warn(

2D embeddings shape: (60, 3)
df_q prepared successfully:   COMPLAINT_ID  CATEGORY     SUBCATEGORY UPDATED_DATE STATE           x  \
0         C001   Billing      Overcharge   2025-01-15    CA  -40.754314
1         C002   Service           Delay   2025-01-20    TX   20.613604
2         C003   Product  Defective Item   2025-01-25    NY   58.592487
3         C004   Support    Unresponsive   2025-01-30    FL  -17.683537
4         C005  Delivery    Missing Item   2025-02-01    IL  -29.198523

            y           z
0   3.1160483   40.358833
1  0.15664104   19.957281
2  -26.991922  -1.0639364
3   53.164185  -58.103943
4  -23.397417  -20.732088

In [8]:
df_q.head()

NameError: name 'df_q' is not defined

#### points

If our gene expression features are called `sidecars`, then what is the embedding layer called? Well it is just the "points" of the plot, so we will store these values in `df_p`.

**NOTE**: we also store conditions with `df_p` as whatever is in this DataFrame will be loaded by `Deepscatter` automatically.

In [10]:
df_p = pipe.get_embedding()
df_p = df_p.join(pipe.adata.obs.conditions)
df_p.head()

             MOCK_1    MOCK_2  MOCK_3   conditions
barcodes
barcode 0  0.272783  0.277263     NaN  condition 0
barcode 1 -0.376359 -1.905994     NaN  condition 1
barcode 2  0.356305  0.017158     NaN  condition 2
barcode 3  0.134571 -0.100901     NaN  condition 3
barcode 4  0.856395 -2.030319     NaN  condition 0

#### Combined
Now we combine `df_p` (points + condition) with `df_s` ("sidecars" i.e. gene expression). This is necessary as for script later on where we need to add the sidecars to already the `quadfeather`-ed (tiled) point data.

In [11]:
df_all = df_p.join(df_s)
df_all.head()

,MOCK_1,MOCK_2,MOCK_3,conditions,gene_symbol 0,gene_symbol 1,gene_symbol 2,gene_symbol 3,gene_symbol 4,gene_symbol 5,...,gene_symbol 90,gene_symbol 91,gene_symbol 92,gene_symbol 93,gene_symbol 94,gene_symbol 95,gene_symbol 96,gene_symbol 97,gene_symbol 98,gene_symbol 99
barcodes,,,,,,,,,,,,,,,,,,,,,
barcode 0,0.272783,0.277263,NaN,condition 0,0.803276,0.244524,-0.192386,-0.800793,-2.016473,0.821837,...,-1.088258,-2.642169,-0.956667,0.238179,-2.116511,-1.038880,0.282109,-1.040906,0.348024,0.703587
barcode 1,-0.376359,-1.905994,NaN,condition 1,0.656503,-2.400139,1.251113,0.512456,0.306186,1.588643,...,-0.395451,1.474536,0.433047,0.067309,1.097640,0.249324,0.538526,0.000884,2.739368,-1.101643
barcode 2,0.356305,0.017158,NaN,condition 2,0.014030,1.228871,1.006785,0.720465,-0.121492,0.115829,...,-0.416621,-0.667497,0.169813,0.311218,1.030311,0.396096,-0.754883,1.440937,0.849603,-0.541365
barcode 3,0.134571,-0.100901,NaN,condition 3,1.219619,0.834831,0.163721,0.343506,-0.164225,-0.095177,...,-1.010034,1.370871,-0.276237,-0.864229,-0.338752,0.555502,-1.301947,0.400086,0.205288,-1.246912
barcode 4,0.856395,-2.030319,NaN,condition 0,-0.355697,-0.515200,-1.566528,0.548676,0.168378,-1.152343,...,0.351259,0.823491,-0.408399,0.725561,-0.438170,-0.834018,-0.025542,1.571137,1.902323,-0.986374

### QuadFeatherRenamer

Note: `quadfeather` and `deepscatter` are both under active development so things change all the time. At the moment `quadfeather` requires that `x` and `y` be in your DataFrame (it doesn't mind if `z` is there too). So this will handle the renaming of our columns.

In [12]:
qfr = QuadFeatherRenamer(df_all)

In [13]:
df_q, renamed = qfr.rename()
renamed

{'MOCK_1': 'x', 'MOCK_2': 'y', 'MOCK_3': 'z'}

In [14]:
from dataclasses import dataclass, field
from typing import Optional, List, Tuple, Union, Any, Dict
import pandas as pd

@dataclass
class DataFrameToMetadata:
    df: pd.DataFrame
    sidecars: Optional[List[str]] = field(default_factory=list)
    embedding: Optional[List[str]] = field(default_factory=lambda: ['x', 'y', 'z'])
    alt_names: Optional[Dict[str, str]] = field(default_factory=dict)
    include_index: Optional[bool] = True

    def __post_init__(self):
        if not self.sidecars:
            self.sidecars = self._default_sidecars()

        if not self.embedding:
            self.embedding = ['x', 'y', 'z']
        elif not all(e in self.embedding for e in ['x', 'y', 'z']):
            raise ValueError('Must have x, y, z in embedding')

    def _default_sidecars(self) -> List[str]:
        return sorted(set(self.df.columns) - set(self.embedding))

    def _do_one(self, name: str, col: pd.Series, is_index: bool = False) -> Tuple[Union[Any, None], Union[Dict[str, Any], None]]:
        success = None
        failure = None

        is_sidecar = name in self.sidecars and name not in self.embedding
        alt_name = self.alt_names.get(name)

        try:
            s2c = SeriesToChannel(col, is_sidecar, alt_name)
            channel = s2c.convert()

            # Ensure categorical type if applicable
            if not is_index and self.df.index.name != name and s2c.is_category():
                channel = s2c.as_category().convert()
                self.df.loc[:, name] = s2c.series.values

            success = channel
        except Exception as e:
            failure = {"name": name, "is_sidecar": is_sidecar, "alt_name": alt_name, "error": e}

        return success, failure

    def convert(self) -> Tuple[dict, List[Dict[str, Dict[str, Any]]]]:
        failed = []
        channels = {}

        if self.include_index:
            name = "index" if self.df.index.name is None else self.df.index.name
            succ, fail = self._do_one(name, pd.Series(self.df.index), is_index=True)
            if succ is not None:
                channels[name] = succ
            else:
                failed.append(fail)

        for name, col in self.df.items():  # Updated from iteritems() to items()
            succ, fail = self._do_one(name, col)
            if succ is not None:
                if name not in channels:
                    channels[name] = succ
            else:
                failed.append(fail)

        return channels, failed

    def to_dict(self) -> dict:
        channels, _ = self.convert()
        return {
            "index": self.df.index.name if self.df.index.name else "index",
            "n_points": len(self.df),
            "embedding": self.embedding,
            "sidecars": self.sidecars,
            "columns_metadata": {k: v.to_dict() for k, v in channels.items()},
            "tiles_dir": None,
        }

    def to_meta(self) -> dict:
        channels, _ = self.convert()
        return {
            "index": self.df.index.name if self.df.index.name else "index",
            "n_points": len(self.df),
            "embedding": self.embedding,
            "sidecars": self.sidecars,
            "columns_metadata": {k: v.to_meta() for k, v in channels.items()},
            "tiles_dir": None,
        }

### DataFrameToMetadata
 
`Deepscatter` is a really nice library; however, it also prefers to have its `plotAPI` method called with as much information as possible. This is a bit of a shame as it means that one you load your data with `deepscatter` you can't compute derived properties (e.g. domain of your data to scale the plot, check for what sidecars are availble, etc). 

The solution to this is simple. In order to have this information availble to us, we will just calculate it now (including which columns were renamed) and store it as metadata to use later

In [15]:
d2m = DataFrameToMetadata(
    df_q, 
    include_index=True,
    embedding='x y z conditions'.split(),
    alt_names={v:k for k,v in renamed.items()}
)

In [16]:
succ, fail = d2m.convert()
len(succ), len(fail)

(105, 0)

In [17]:
meta = d2m.to_meta()

print(meta)

{'index': 'barcodes', 'n_points': 1000, 'embedding': ['x', 'y', 'z', 'conditions'], 'sidecars': ['gene_symbol 0', 'gene_symbol 1', 'gene_symbol 10', 'gene_symbol 11', 'gene_symbol 12', 'gene_symbol 13', 'gene_symbol 14', 'gene_symbol 15', 'gene_symbol 16', 'gene_symbol 17', 'gene_symbol 18', 'gene_symbol 19', 'gene_symbol 2', 'gene_symbol 20', 'gene_symbol 21', 'gene_symbol 22', 'gene_symbol 23', 'gene_symbol 24', 'gene_symbol 25', 'gene_symbol 26', 'gene_symbol 27', 'gene_symbol 28', 'gene_symbol 29', 'gene_symbol 3', 'gene_symbol 30', 'gene_symbol 31', 'gene_symbol 32', 'gene_symbol 33', 'gene_symbol 34', 'gene_symbol 35', 'gene_symbol 36', 'gene_symbol 37', 'gene_symbol 38', 'gene_symbol 39', 'gene_symbol 4', 'gene_symbol 40', 'gene_symbol 41', 'gene_symbol 42', 'gene_symbol 43', 'gene_symbol 44', 'gene_symbol 45', 'gene_symbol 46', 'gene_symbol 47', 'gene_symbol 48', 'gene_symbol 49', 'gene_symbol 5', 'gene_symbol 50', 'gene_symbol 51', 'gene_symbol 52', 'gene_symbol 53', 'gene_symbol 54', 'gene_symbol 55', 'gene_symbol 56', 'gene_symbol 57', 'gene_symbol 58', 'gene_symbol 59', 'gene_symbol 6', 'gene_symbol 60', 'gene_symbol 61', 'gene_symbol 62', 'gene_symbol 63', 'gene_symbol 64', 'gene_symbol 65', 'gene_symbol 66', 'gene_symbol 67', 'gene_symbol 68', 'gene_symbol 69', 'gene_symbol 7', 'gene_symbol 70', 'gene_symbol 71', 'gene_symbol 72', 'gene_symbol 73', 'gene_symbol 74', 'gene_symbol 75', 'gene_symbol 76', 'gene_symbol 77', 'gene_symbol 78', 'gene_symbol 79', 'gene_symbol 8', 'gene_symbol 80', 'gene_symbol 81', 'gene_symbol 82', 'gene_symbol 83', 'gene_symbol 84', 'gene_symbol 85', 'gene_symbol 86', 'gene_symbol 87', 'gene_symbol 88', 'gene_symbol 89', 'gene_symbol 9', 'gene_symbol 90', 'gene_symbol 91', 'gene_symbol 92', 'gene_symbol 93', 'gene_symbol 94', 'gene_symbol 95', 'gene_symbol 96', 'gene_symbol 97', 'gene_symbol 98', 'gene_symbol 99'], 'columns_metadata': {'barcodes': {'field': 'barcodes', 'range': None, 'domain': [0, 999], 'type': 'CategoricalColorChannel'}, 'x': {'field': 'x', 'transform': 'literal', 'range': None, 'domain': [-3.4190877321892863, 3.324598859809977], 'human': 'MOCK_1', 'type': 'BasicChannel'}, 'y': {'field': 'y', 'transform': 'literal', 'range': None, 'domain': [-2.999686840152621, 3.360224467233471], 'human': 'MOCK_2', 'type': 'BasicChannel'}, 'z': {'field': 'z', 'transform': 'literal', 'range': None, 'domain': [nan, nan], 'human': 'MOCK_3', 'type': 'BasicChannel'}, 'conditions': {'field': 'conditions', 'range': None, 'domain': [0, 3], 'categories': ['condition 0', 'condition 1', 'condition 2', 'condition 3'], 'type': 'CategoricalColorChannel'}, 'gene_symbol 0': {'field': 'gene_symbol 0', 'transform': 'literal', 'range': None, 'domain': [-2.8726536211340687, 3.322714129644035], 'type': 'BasicChannel'}, 'gene_symbol 1': {'field': 'gene_symbol 1', 'transform': 'literal', 'range': None, 'domain': [-3.2714798120210418, 3.419827815222448], 'type': 'BasicChannel'}, 'gene_symbol 2': {'field': 'gene_symbol 2', 'transform': 'literal', 'range': None, 'domain': [-3.1287668374932447, 3.450532674563943], 'type': 'BasicChannel'}, 'gene_symbol 3': {'field': 'gene_symbol 3', 'transform': 'literal', 'range': None, 'domain': [-3.458724863267293, 3.4096639107676165], 'type': 'BasicChannel'}, 'gene_symbol 4': {'field': 'gene_symbol 4', 'transform': 'literal', 'range': None, 'domain': [-3.043177889855359, 3.0510106652417073], 'type': 'BasicChannel'}, 'gene_symbol 5': {'field': 'gene_symbol 5', 'transform': 'literal', 'range': None, 'domain': [-3.289258774052464, 3.3177099793812332], 'type': 'BasicChannel'}, 'gene_symbol 6': {'field': 'gene_symbol 6', 'transform': 'literal', 'range': None, 'domain': [-3.039160322207666, 2.994895328329202], 'type': 'BasicChannel'}, 'gene_symbol 7': {'field': 'gene_symbol 7', 'transform': 'literal', 'range': None, 'domain': [-2.8326337440197533, 3.355107960362661], 'type': 'BasicChannel'}, 'gene_symbol 8': {'field': 'gene_symbol 8', 'transform': 'literal', 'range': None, 'domain': [-3.051570952948905, 3.558603518580014], 'type': 'BasicChannel'}, 'gene_symbol 9': {'field': 'gene_symbol 9', 'transform': 'literal', 'range': None, 'domain': [-3.1144991851331985, 3.917955022699108], 'type': 'BasicChannel'}, 'gene_symbol 10': {'field': 'gene_symbol 10', 'transform': 'literal', 'range': None, 'domain': [-3.468398339571899, 3.5427671790394144], 'type': 'BasicChannel'}, 'gene_symbol 11': {'field': 'gene_symbol 11', 'transform': 'literal', 'range': None, 'domain': [-3.2929886686505108, 3.5392130574679013], 'type': 'BasicChannel'}, 'gene_symbol 12': {'field': 'gene_symbol 12', 'transform': 'literal', 'range': None, 'domain': [-3.3204912194728715, 3.6727567739896654], 'type': 'BasicChannel'}, 'gene_symbol 13': {'field': 'gene_symbol 13', 'transform': 'literal', 'range': None, 'domain': [-3.2956323755143426, 2.99833954183922], 'type': 'BasicChannel'}, 'gene_symbol 14': {'field': 'gene_symbol 14', 'transform': 'literal', 'range': None, 'domain': [-3.455926619670607, 4.169615179156606], 'type': 'BasicChannel'}, 'gene_symbol 15': {'field': 'gene_symbol 15', 'transform': 'literal', 'range': None, 'domain': [-2.6984919705582397, 4.043509191460944], 'type': 'BasicChannel'}, 'gene_symbol 16': {'field': 'gene_symbol 16', 'transform': 'literal', 'range': None, 'domain': [-2.7953658278897198, 3.173450178805924], 'type': 'BasicChannel'}, 'gene_symbol 17': {'field': 'gene_symbol 17', 'transform': 'literal', 'range': None, 'domain': [-3.8838834964576403, 2.7615387016149837], 'type': 'BasicChannel'}, 'gene_symbol 18': {'field': 'gene_symbol 18', 'transform': 'literal', 'range': None, 'domain': [-2.955157315517716, 4.027511938634783], 'type': 'BasicChannel'}, 'gene_symbol 19': {'field': 'gene_symbol 19', 'transform': 'literal', 'range': None, 'domain': [-3.177930605740288, 2.7831242258459437], 'type': 'BasicChannel'}, 'gene_symbol 20': {'field': 'gene_symbol 20', 'transform': 'literal', 'range': None, 'domain': [-3.3197158972695444, 3.4257232591241986], 'type': 'BasicChannel'}, 'gene_symbol 21': {'field': 'gene_symbol 21', 'transform': 'literal', 'range': None, 'domain': [-3.3737187166397735, 3.6696765147731525], 'type': 'BasicChannel'}, 'gene_symbol 22': {'field': 'gene_symbol 22', 'transform': 'literal', 'range': None, 'domain': [-2.784141792492048, 2.788987640753347], 'type': 'BasicChannel'}, 'gene_symbol 23': {'field': 'gene_symbol 23', 'transform': 'literal', 'range': None, 'domain': [-2.9923835301460073, 3.1409898326992365], 'type': 'BasicChannel'}, 'gene_symbol 24': {'field': 'gene_symbol 24', 'transform': 'literal', 'range': None, 'domain': [-3.4888684843109545, 2.9635064767265598], 'type': 'BasicChannel'}, 'gene_symbol 25': {'field': 'gene_symbol 25', 'transform': 'literal', 'range': None, 'domain': [-2.80814549024269, 3.080400233997811], 'type': 'BasicChannel'}, 'gene_symbol 26': {'field': 'gene_symbol 26', 'transform': 'literal', 'range': None, 'domain': [-3.043502391300655, 3.0465935778181357], 'type': 'BasicChannel'}, 'gene_symbol 27': {'field': 'gene_symbol 27', 'transform': 'literal', 'range': None, 'domain': [-3.4650519948726983, 2.810884534590169], 'type': 'BasicChannel'}, 'gene_symbol 28': {'field': 'gene_symbol 28', 'transform': 'literal', 'range': None, 'domain': [-3.1612387167127856, 2.9270514285965774], 'type': 'BasicChannel'}, 'gene_symbol 29': {'field': 'gene_symbol 29', 'transform': 'literal', 'range': None, 'domain': [-3.1926961713019653, 2.9276623977563276], 'type': 'BasicChannel'}, 'gene_symbol 30': {'field': 'gene_symbol 30', 'transform': 'literal', 'range': None, 'domain': [-3.10615700941724, 3.051098574932163], 'type': 'BasicChannel'}, 'gene_symbol 31': {'field': 'gene_symbol 31', 'transform': 'literal', 'range': None, 'domain': [-3.127513129670328, 3.132152647923636], 'type': 'BasicChannel'}, 'gene_symbol 32': {'field': 'gene_symbol 32', 'transform': 'literal', 'range': None, 'domain': [-2.775434688222105, 2.5135231185133406], 'type': 'BasicChannel'}, 'gene_symbol 33': {'field': 'gene_symbol 33', 'transform': 'literal', 'range': None, 'domain': [-3.14829601261263, 2.978465308572233], 'type': 'BasicChannel'}, 'gene_symbol 34': {'field': 'gene_symbol 34', 'transform': 'literal', 'range': None, 'domain': [-3.1997984555604346, 3.3795359707653465], 'type': 'BasicChannel'}, 'gene_symbol 35': {'field': 'gene_symbol 35', 'transform': 'literal', 'range': None, 'domain': [-2.7646187606319534, 3.816350274311653], 'type': 'BasicChannel'}, 'gene_symbol 36': {'field': 'gene_symbol 36', 'transform': 'literal', 'range': None, 'domain': [-2.6923690265325377, 2.92893324693254], 'type': 'BasicChannel'}, 'gene_symbol 37': {'field': 'gene_symbol 37', 'transform': 'literal', 'range': None, 'domain': [-3.207296066820701, 4.137382287207335], 'type': 'BasicChannel'}, 'gene_symbol 38': {'field': 'gene_symbol 38', 'transform': 'literal', 'range': None, 'domain': [-3.418469027975687, 3.5483885908702733], 'type': 'BasicChannel'}, 'gene_symbol 39': {'field': 'gene_symbol 39', 'transform': 'literal', 'range': None, 'domain': [-2.8783550967392904, 2.84063923375484], 'type': 'BasicChannel'}, 'gene_symbol 40': {'field': 'gene_symbol 40', 'transform': 'literal', 'range': None, 'domain': [-3.2371192835495077, 2.977555439071652], 'type': 'BasicChannel'}, 'gene_symbol 41': {'field': 'gene_symbol 41', 'transform': 'literal', 'range': None, 'domain': [-3.9949926997588747, 3.3936289079097186], 'type': 'BasicChannel'}, 'gene_symbol 42': {'field': 'gene_symbol 42', 'transform': 'literal', 'range': None, 'domain': [-3.640926944248783, 3.255846806625036], 'type': 'BasicChannel'}, 'gene_symbol 43': {'field': 'gene_symbol 43', 'transform': 'literal', 'range': None, 'domain': [-3.3146088611294795, 3.2333534308599683], 'type': 'BasicChannel'}, 'gene_symbol 44': {'field': 'gene_symbol 44', 'transform': 'literal', 'range': None, 'domain': [-3.069997448279107, 3.625565412600804], 'type': 'BasicChannel'}, 'gene_symbol 45': {'field': 'gene_symbol 45', 'transform': 'literal', 'range': None, 'domain': [-3.67829462231323, 3.195580801556475], 'type': 'BasicChannel'}, 'gene_symbol 46': {'field': 'gene_symbol 46', 'transform': 'literal', 'range': None, 'domain': [-3.150956363323129, 2.8582989538481645], 'type': 'BasicChannel'}, 'gene_symbol 47': {'field': 'gene_symbol 47', 'transform': 'literal', 'range': None, 'domain': [-3.134574761269947, 3.112758938650633], 'type': 'BasicChannel'}, 'gene_symbol 48': {'field': 'gene_symbol 48', 'transform': 'literal', 'range': None, 'domain': [-3.479013563394124, 2.7180944006632526], 'type': 'BasicChannel'}, 'gene_symbol 49': {'field': 'gene_symbol 49', 'transform': 'literal', 'range': None, 'domain': [-3.3692835800090752, 3.534571619054511], 'type': 'BasicChannel'}, 'gene_symbol 50': {'field': 'gene_symbol 50', 'transform': 'literal', 'range': None, 'domain': [-3.7149044173363355, 3.7232315930181348], 'type': 'BasicChannel'}, 'gene_symbol 51': {'field': 'gene_symbol 51', 'transform': 'literal', 'range': None, 'domain': [-3.025221143922459, 3.269935204844063], 'type': 'BasicChannel'}, 'gene_symbol 52': {'field': 'gene_symbol 52', 'transform': 'literal', 'range': None, 'domain': [-3.2506138320346554, 2.931836771879166], 'type': 'BasicChannel'}, 'gene_symbol 53': {'field': 'gene_symbol 53', 'transform': 'literal', 'range': None, 'domain': [-4.088085477221139, 3.1977819242901515], 'type': 'BasicChannel'}, 'gene_symbol 54': {'field': 'gene_symbol 54', 'transform': 'literal', 'range': None, 'domain': [-2.9796326260706487, 3.212337609592786], 'type': 'BasicChannel'}, 'gene_symbol 55': {'field': 'gene_symbol 55', 'transform': 'literal', 'range': None, 'domain': [-3.0715727406777615, 3.1936834246794477], 'type': 'BasicChannel'}, 'gene_symbol 56': {'field': 'gene_symbol 56', 'transform': 'literal', 'range': None, 'domain': [-3.4825523049620233, 2.892551961384045], 'type': 'BasicChannel'}, 'gene_symbol 57': {'field': 'gene_symbol 57', 'transform': 'literal', 'range': None, 'domain': [-2.830501563889266, 3.6430903099046885], 'type': 'BasicChannel'}, 'gene_symbol 58': {'field': 'gene_symbol 58', 'transform': 'literal', 'range': None, 'domain': [-2.828484552835112, 2.918642452996042], 'type': 'BasicChannel'}, 'gene_symbol 59': {'field': 'gene_symbol 59', 'transform': 'literal', 'range': None, 'domain': [-3.138415531310427, 3.026489016975104], 'type': 'BasicChannel'}, 'gene_symbol 60': {'field': 'gene_symbol 60', 'transform': 'literal', 'range': None, 'domain': [-3.154899409239191, 3.0654158534037252], 'type': 'BasicChannel'}, 'gene_symbol 61': {'field': 'gene_symbol 61', 'transform': 'literal', 'range': None, 'domain': [-3.1218038445642584, 2.9570670350444463], 'type': 'BasicChannel'}, 'gene_symbol 62': {'field': 'gene_symbol 62', 'transform': 'literal', 'range': None, 'domain': [-3.56428327728911, 2.8722839775885256], 'type': 'BasicChannel'}, 'gene_symbol 63': {'field': 'gene_symbol 63', 'transform': 'literal', 'range': None, 'domain': [-3.514487599003208, 3.1404789306527405], 'type': 'BasicChannel'}, 'gene_symbol 64': {'field': 'gene_symbol 64', 'transform': 'literal', 'range': None, 'domain': [-3.3791271169759396, 3.299954920009794], 'type': 'BasicChannel'}, 'gene_symbol 65': {'field': 'gene_symbol 65', 'transform': 'literal', 'range': None, 'domain': [-3.7797279199934284, 4.607829270878947], 'type': 'BasicChannel'}, 'gene_symbol 66': {'field': 'gene_symbol 66', 'transform': 'literal', 'range': None, 'domain': [-3.4689124600855745, 2.8066284830278394], 'type': 'BasicChannel'}, 'gene_symbol 67': {'field': 'gene_symbol 67', 'transform': 'literal', 'range': None, 'domain': [-3.0297038845356274, 3.6503958289045957], 'type': 'BasicChannel'}, 'gene_symbol 68': {'field': 'gene_symbol 68', 'transform': 'literal', 'range': None, 'domain': [-2.7840615907273087, 3.339897800085192], 'type': 'BasicChannel'}, 'gene_symbol 69': {'field': 'gene_symbol 69', 'transform': 'literal', 'range': None, 'domain': [-3.2533662173985882, 3.1679093426737657], 'type': 'BasicChannel'}, 'gene_symbol 70': {'field': 'gene_symbol 70', 'transform': 'literal', 'range': None, 'domain': [-4.079209883152844, 3.745388392006086], 'type': 'BasicChannel'}, 'gene_symbol 71': {'field': 'gene_symbol 71', 'transform': 'literal', 'range': None, 'domain': [-3.416736233477906, 3.5639547353298404], 'type': 'BasicChannel'}, 'gene_symbol 72': {'field': 'gene_symbol 72', 'transform': 'literal', 'range': None, 'domain': [-3.0743679501941132, 2.7802286584585714], 'type': 'BasicChannel'}, 'gene_symbol 73': {'field': 'gene_symbol 73', 'transform': 'literal', 'range': None, 'domain': [-2.784938076387566, 3.2440732954944513], 'type': 'BasicChannel'}, 'gene_symbol 74': {'field': 'gene_symbol 74', 'transform': 'literal', 'range': None, 'domain': [-2.9518904436363846, 3.4246329065025938], 'type': 'BasicChannel'}, 'gene_symbol 75': {'field': 'gene_symbol 75', 'transform': 'literal', 'range': None, 'domain': [-3.9176695108686292, 3.388148113470775], 'type': 'BasicChannel'}, 'gene_symbol 76': {'field': 'gene_symbol 76', 'transform': 'literal', 'range': None, 'domain': [-3.4566060197795108, 2.8178118846403777], 'type': 'BasicChannel'}, 'gene_symbol 77': {'field': 'gene_symbol 77', 'transform': 'literal', 'range': None, 'domain': [-3.8261998634102965, 3.389972620677373], 'type': 'BasicChannel'}, 'gene_symbol 78': {'field': 'gene_symbol 78', 'transform': 'literal', 'range': None, 'domain': [-3.0940332761866256, 3.1121866875668425], 'type': 'BasicChannel'}, 'gene_symbol 79': {'field': 'gene_symbol 79', 'transform': 'literal', 'range': None, 'domain': [-3.3087313364557516, 3.2102307862490207], 'type': 'BasicChannel'}, 'gene_symbol 80': {'field': 'gene_symbol 80', 'transform': 'literal', 'range': None, 'domain': [-3.4401768532790182, 4.1732381599886414], 'type': 'BasicChannel'}, 'gene_symbol 81': {'field': 'gene_symbol 81', 'transform': 'literal', 'range': None, 'domain': [-3.1335903995545697, 3.1298034579730536], 'type': 'BasicChannel'}, 'gene_symbol 82': {'field': 'gene_symbol 82', 'transform': 'literal', 'range': None, 'domain': [-3.867416590582338, 3.9014408827410683], 'type': 'BasicChannel'}, 'gene_symbol 83': {'field': 'gene_symbol 83', 'transform': 'literal', 'range': None, 'domain': [-3.40674255610338, 3.4214308629606287], 'type': 'BasicChannel'}, 'gene_symbol 84': {'field': 'gene_symbol 84', 'transform': 'literal', 'range': None, 'domain': [-3.6989973361768866, 2.9756988691270605], 'type': 'BasicChannel'}, 'gene_symbol 85': {'field': 'gene_symbol 85', 'transform': 'literal', 'range': None, 'domain': [-3.1149831229344365, 3.3019296261391706], 'type': 'BasicChannel'}, 'gene_symbol 86': {'field': 'gene_symbol 86', 'transform': 'literal', 'range': None, 'domain': [-3.048925119193533, 3.324178956589309], 'type': 'BasicChannel'}, 'gene_symbol 87': {'field': 'gene_symbol 87', 'transform': 'literal', 'range': None, 'domain': [-2.8761792694998394, 3.2065491734687868], 'type': 'BasicChannel'}, 'gene_symbol 88': {'field': 'gene_symbol 88', 'transform': 'literal', 'range': None, 'domain': [-3.0790714036515863, 2.929701570620138], 'type': 'BasicChannel'}, 'gene_symbol 89': {'field': 'gene_symbol 89', 'transform': 'literal', 'range': None, 'domain': [-2.9035995101308223, 2.8624983910383386], 'type': 'BasicChannel'}, 'gene_symbol 90': {'field': 'gene_symbol 90', 'transform': 'literal', 'range': None, 'domain': [-3.051684044340277, 3.255964079307987], 'type': 'BasicChannel'}, 'gene_symbol 91': {'field': 'gene_symbol 91', 'transform': 'literal', 'range': None, 'domain': [-3.2574472253114415, 3.1086927958598953], 'type': 'BasicChannel'}, 'gene_symbol 92': {'field': 'gene_symbol 92', 'transform': 'literal', 'range': None, 'domain': [-3.3176022443803643, 2.9897621213047967], 'type': 'BasicChannel'}, 'gene_symbol 93': {'field': 'gene_symbol 93', 'transform': 'literal', 'range': None, 'domain': [-3.2108098611202265, 3.0166540261811026], 'type': 'BasicChannel'}, 'gene_symbol 94': {'field': 'gene_symbol 94', 'transform': 'literal', 'range': None, 'domain': [-3.1320202639537085, 3.1735800768745857], 'type': 'BasicChannel'}, 'gene_symbol 95': {'field': 'gene_symbol 95', 'transform': 'literal', 'range': None, 'domain': [-3.201717738234616, 3.211112426830182], 'type': 'BasicChannel'}, 'gene_symbol 96': {'field': 'gene_symbol 96', 'transform': 'literal', 'range': None, 'domain': [-3.993009655350547, 2.999406406803856], 'type': 'BasicChannel'}, 'gene_symbol 97': {'field': 'gene_symbol 97', 'transform': 'literal', 'range': None, 'domain': [-3.3286769605858315, 3.6246611678240637], 'type': 'BasicChannel'}, 'gene_symbol 98': {'field': 'gene_symbol 98', 'transform': 'literal', 'range': None, 'domain': [-3.3721818843981577, 2.739367611025368], 'type': 'BasicChannel'}, 'gene_symbol 99': {'field': 'gene_symbol 99', 'transform': 'literal', 'range': None, 'domain': [-3.0103962740118484, 3.056575698373479], 'type': 'BasicChannel'}}, 'tiles_dir': None}

## Quadfeather Workflow

Now we can now run through thte `quadfeather` workflow right here in the notebook.

### 0) setup

In [18]:
# dump everything to downloads for easy access
outdir = os.path.expanduser('~/Downloads/featherplot')
qf_dir = os.path.join(outdir, 'tiles')
if not os.path.isdir(qf_dir):
    os.makedirs(qf_dir)


p_file = os.path.join(outdir, 'points.parquet')
# NOTE: we never use s_file
# s_file = os.path.join(outdir, 'extras.parquet')
f_file = os.path.join(qf_dir, 'sidecars.feather')
m_file = os.path.join(outdir, 'meta.yml')


tile_size = 1000

### 1) create tiles

In [19]:
d2m.df.drop(columns=df_s.columns).to_parquet(p_file)
# d2m.df.drop(columns=d2m.embedding).to_parquet(s_file)

In [20]:
!quadfeather --files {p_file} \
             --tile_size {tile_size} \
             --destination {qf_dir}

### 2) make single file

In [21]:
feather.write_feather(d2m.df.drop(columns=d2m.embedding), f_file)

### 3) run `add_sidecars.py`

In [24]:
tileset = Tileset(Path(qf_dir))
print(f_file)
# tileset.add_sidecars(f_file, d2m.df.index.name)

/home/hm3/Downloads/featherplot/tiles/sidecars.feather

note we copied `add_sidecars.py` so you can use it directly from this library

In [25]:
!featherplot add-sidecars --tileset {qf_dir}\
                         --sidecar {f_file} --key {d2m.df.index.name};

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/hm3/Desktop/complaint-plotter/.venv/lib/python3.13/site-packages/feath │
│ erplot/commands.py:37 in add_sidecars                                        │
│                                                                              │
│   34 │   verbose:bool = typer.Option(False, '--verbose', '-v', help='Print v │
│   35 ):                                                                      │
│   36 │   tileset = Tileset(tileset)                                          │
│ ❱ 37 │   tileset.add_sidecars(sidecar, key, verbose=verbose)                 │
│   38                                                                         │
│   39 # %% ../nbs/08_commands.ipynb 7                                         │
│   40 @app.command()                                                          │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │     key = 'barcodes'                                                     │ │
│ │ sidecar = PosixPath('/home/hm3/Downloads/featherplot/tiles/sidecars.fea… │ │
│ │ tileset = <featherplot.deepscatter.Tileset object at 0x72e4c82da3c0>     │ │
│ │ verbose = False                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /home/hm3/Desktop/complaint-plotter/.venv/lib/python3.13/site-packages/feath │
│ erplot/deepscatter.py:100 in add_sidecars                                    │
│                                                                              │
│    97 │   root = feather.read_table(rootpath)                                │
│    98 │   locations = {column: column for column in sidecar_table.column_nam │
│    99 │   # Copy the existing sidecar locations, if any.                     │
│ ❱ 100 │   locations = {**json.loads(root.schema.metadata.get(b"sidecars", b" │
│   101 │   root = root.replace_schema_metadata({**root.schema.metadata, b"sid │
│   102 │   feather.write_feather(root, rootpath, compression='uncompressed')  │
│   103                                                                        │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │         all_ixes = <pyarrow.lib.ChunkedArray object at 0x72e4cf7c1d20>   │ │
│ │                    [                                                     │ │
│ │                      [                                                   │ │
│ │                    │   0,                                                │ │
│ │                    │   1,                                                │ │
│ │                    │   2,                                                │ │
│ │                    │   3,                                                │ │
│ │                    │   4,                                                │ │
│ │                    │   ...                                               │ │
│ │                    │   995,                                              │ │
│ │                    │   996,                                              │ │
│ │                    │   997,                                              │ │
│ │                    │   998,                                              │ │
│ │                    │   999                                               │ │
│ │                      ]                                                   │ │
│ │                    ]                                                     │ │
│ │           column = 'barcodes'                                            │ │
│ │              end = 1000                                                  │ │
│ │             file = PosixPath('/home/hm3/Downloads/featherplot/tiles/0/0… │ │
│ │         filename = None                                                  │ │
│ │             fout = PosixPath('/home/hm3/Downloads/featherplot/tiles/0/0… │ │
│ │                    99.feather')                                          │ │
│ │                i = 0                                                     │ │
│ │             ixes = <pyarrow.lib.ChunkedArray object at 0x72e4cf7c1c00>   │ │
│ │                    [                                                     │ │
│ │                      [                                                   │ │
│ │                    │   0,                                                │ │
│ │                    │   1,                                                │ │
│ │                    │   2,                                                │ │
│ │                    │   3,                                                │ │
│ │                    │   4,                                                │ │
│ │                    │   ...                                               │ │
│ │                    │   995,                                              │ │
│ │                    │   996,                                              │ │
│ │                    │   997,                                              │ │
│ │                    │   998,                                              │ │
│ │                    │   999                                               │ │
│ │                      ]                                                   │ │
│ │                    ]                                                     │ │
│ │              key = 'barcodes'                                            │ │
│ │        locations = {                                                     │ │
│ │                    │   'gene_symbol 0': 'gene_symbol 0',                 │ │
│ │                    │   'gene_symbol 1': 'gene_symbol 1',                 │ │
│ │                    │   'gene_symbol 2': 'gene_symbol 2',                 │ │
│ │                    │   'gene_symbol 3': 'gene_symbol 3',                 │ │
│ │                    │   'gene_symbol 4': 'gene_symbol 4',                 │ │
│ │                    │   'gene_symbol 5': 'gene_symbol 5',                 │ │
│ │                    │   'gene_symbol 6': 'gene_symbol 6',                 │ │
│ │                    │   'gene_symbol 7': 'gene_symbol 7',                 │ │
│ │                    │   'gene_symbol 8': 'gene_symbol 8',                 │ │
│ │                    │   'gene_symbol 9': 'gene_symbol 9',                 │ │
│ │                    │   ... +90                                           │ │
│ │                    }                                                     │ │
│ │    master_lookup = [                                                     │ │
│ │                    │   pyarrow.Table                                     │ │
│ │                    barcodes: string                                      │ │
│ │                    ----                                                  │ │
│ │                    barcodes: [["barcode 0","barcode 1","barcode          │ │
│ │                    2","barcode 3","barcode 4",...,"barcode 995","barcode │ │
│ │                    996","barcode 997","barcode 998","barcode 999"]]      │ │
│ │                    ]                                                     │ │
│ │ master_lookup_tb = pyarrow.Table                                         │ │
│ │                    barcodes: string                                      │ │
│ │                    ----                                                  │ │
│ │                    barcodes: [["barcode 0","barcode 1","barcode          │ │
│ │                    2","barcode 3","barcode 4",...,"barcode 995","barcode │ │
│ │                    996","barcode 997","barcode 998","barcode 999"]]      │ │
│ │             root = pyarrow.Table                                         │ │
│ │                    x: double                                             │ │
│ │                    y: double                                             │ │
│ │                    z: double                                             │ │
│ │                    conditions: string                                    │ │
│ │                    barcodes: string                                      │ │
│ │                    ix: uint64                                            │ │
│ │                    ----                                                  │ │
│ │                    x:                                                    │ │
│ │                    [[0.2727830344249892,-0.37635917939641356,0.35630534… │ │
│ │                    y:                                                    │ │
│ │                    [[0.27726328424577695,-1.9059936980070764,0.01715779… │ │
│ │                    z:                                                    │ │
│ │                    [[null,null,null,null,null,...,null,null,null,null,n… │ │
│ │                    conditions: [["condition 0","condition 1","condition  │ │
│ │                    2","condition 3","condition 0",...,"condition         │ │
│ │                    3","condition 0","condition 1","condition             │ │
│ │                    2","condition 3"]]                                    │ │
│ │                    barcodes: [["barcode 0","barcode 1","barcode          │ │
│ │                    2","barcode 3","barcode 4",...,"barcode 995","barcode │ │
│ │                    996","barcode 997","barcode 998","barcode 999"]]      │ │
│ │                    ix: [[0,1,2,3,4,...,995,996,997,998,999]]             │ │
│ │         rootpath = PosixPath('/home/hm3/Downloads/featherplot/tiles/0/0… │ │
│ │             self = <featherplot.deepscatter.Tileset object at            │ │
│ │                    0x72e4c82da3c0>                                       │ │
│ │          sidecar = PosixPath('/home/hm3/Downloads/featherplot/tiles/sid… │ │
│ │    sidecar_table = pyarrow.Table                                         │ │
│ │                    gene_symbol 0: double                                 │ │
│ │                    gene_symbol 1: double                                 │ │
│ │                    gene_symbol 2: double                                 │ │
│ │                    gene_symbol 3: double                                 │ │
│ │                    gene_symbol 4: double                                 │ │
│ │                    gene_symbol 5: double                                 │ │
│ │                    gene_symbol 6: double                                 │ │
│ │                    gene_symbol 7: double                                 │ │
│ │                    gene_symbol 8: double                                 │ │
│ │                    gene_symbol 9: double                                 │ │
│ │                    gene_symbol 10: double                                │ │
│ │                    gene_symbol 11: double                                │ │
│ │                    gene_symbol 12: double                                │ │
│ │                    gene_symbol 13: double                                │ │
│ │                    gene_symbol 14: double                                │ │
│ │                    gene_symbol 15: double                                │ │
│ │                    gene_symbol 16: double                                │ │
│ │                    gene_symbol 17: double                                │ │
│ │                    gene_symbol 18: double                                │ │
│ │                    gene_symbol 19: double                                │ │
│ │                    gene_symbol 20: double                                │ │
│ │                    gene_symbol 21: double                                │ │
│ │                    gene_symbol 22: double                                │ │
│ │                    gene_symbol 23: double                                │ │
│ │                    gene_symbol 24: double                                │ │
│ │                    gene_symbol 25: double                                │ │
│ │                    gene_symbol 26: double                                │ │
│ │                    gene_symbol 27: double                                │ │
│ │                    gene_symbol 28: double                                │ │
│ │                    gene_symbol 29: double                                │ │
│ │                    gene_symbol 30: double                                │ │
│ │                    gene_symbol 31: double                                │ │
│ │                    gene_symbol 32: double                                │ │
│ │                    gene_symbol 33: double                                │ │
│ │                    gene_symbol 34: double                                │ │
│ │                    gene_symbol 35: double                                │ │
│ │                    gene_symbol 36: double                                │ │
│ │                    gene_symbol 37: double                                │ │
│ │                    gene_symbol 38: double                                │ │
│ │                    gene_symbol 39: double                                │ │
│ │                    gene_symbol 40: double                                │ │
│ │                    gene_symbol 41: double                                │ │
│ │                    gene_symbol 42: double                                │ │
│ │                    gene_symbol 43: double                                │ │
│ │                    gene_symbol 44: double                                │ │
│ │                    gene_symbol 45: double                                │ │
│ │                    gene_symbol 46: double                                │ │
│ │                    gene_symbol 47: double                                │ │
│ │                    gene_symbol 48: double                                │ │
│ │                    gene_symbol 49: double                                │ │
│ │                    gene_symbol 50: double                                │ │
│ │                    gene_symbol 51: double                                │ │
│ │                    gene_symbol 52: double                                │ │
│ │                    gene_symbol 53: double                                │ │
│ │                    gene_symbol 54: double                                │ │
│ │                    gene_symbol 55: double                                │ │
│ │                    gene_symbol 56: double                                │ │
│ │                    gene_symbol 57: double                                │ │
│ │                    gene_symbol 58: double                                │ │
│ │                    gene_symbol 59: double                                │ │
│ │                    gene_symbol 60: double                                │ │
│ │                    gene_symbol 61: double                                │ │
│ │                    gene_symbol 62: double                                │ │
│ │                    gene_symbol 63: double                                │ │
│ │                    gene_symbol 64: double                                │ │
│ │                    gene_symbol 65: double                                │ │
│ │                    gene_symbol 66: double                                │ │
│ │                    gene_symbol 67: double                                │ │
│ │                    gene_symbol 68: double                                │ │
│ │                    gene_symbol 69: double                                │ │
│ │                    gene_symbol 70: double                                │ │
│ │                    gene_symbol 71: double                                │ │
│ │                    gene_symbol 72: double                                │ │
│ │                    gene_symbol 73: double                                │ │
│ │                    gene_symbol 74: double                                │ │
│ │                    gene_symbol 75: double                                │ │
│ │                    gene_symbol 76: double                                │ │
│ │                    gene_symbol 77: double                                │ │
│ │                    gene_symbol 78: double                                │ │
│ │                    gene_symbol 79: double                                │ │
│ │                    gene_symbol 80: double                                │ │
│ │                    gene_symbol 81: double                                │ │
│ │                    gene_symbol 82: double                                │ │
│ │                    gene_symbol 83: double                                │ │
│ │                    gene_symbol 84: double                                │ │
│ │                    gene_symbol 85: double                                │ │
│ │                    gene_symbol 86: double                                │ │
│ │                    gene_symbol 87: double                                │ │
│ │                    gene_symbol 88: double                                │ │
│ │                    gene_symbol 89: double                                │ │
│ │                    gene_symbol 90: double                                │ │
│ │                    gene_symbol 91: double                                │ │
│ │                    gene_symbol 92: double                                │ │
│ │                    gene_symbol 93: double                                │ │
│ │                    gene_symbol 94: double                                │ │
│ │                    gene_symbol 95: double                                │ │
│ │                    gene_symbol 96: double                                │ │
│ │                    gene_symbol 97: double                                │ │
│ │                    gene_symbol 98: double                                │ │
│ │                    gene_symbol 99: double                                │ │
│ │                    barcodes: string                                      │ │
│ │                    ----                                                  │ │
│ │                    gene_symbol 0:                                        │ │
│ │                    [[0.8032761324289021,0.6565031584138736,0.0140296290… │ │
│ │                    gene_symbol 1:                                        │ │
│ │                    [[0.24452404390723856,-2.400139248038457,1.228870537… │ │
│ │                    gene_symbol 2:                                        │ │
│ │                    [[-0.19238553809185344,1.2511134921616305,1.00678461… │ │
│ │                    gene_symbol 3:                                        │ │
│ │                    [[-0.8007932148553892,0.5124564011742616,0.720464818… │ │
│ │                    gene_symbol 4:                                        │ │
│ │                    [[-2.0164725829288708,0.3061862952770352,-0.12149186… │ │
│ │                    gene_symbol 5:                                        │ │
│ │                    [[0.8218372902734096,1.5886426869435526,0.1158293233… │ │
│ │                    gene_symbol 6:                                        │ │
│ │                    [[-0.2982542064371027,-0.8825127054915716,0.69549784… │ │
│ │                    gene_symbol 7:                                        │ │
│ │                    [[1.246355057245149,0.2658822450512009,-0.8963773103… │ │
│ │                    gene_symbol 8:                                        │ │
│ │                    [[0.35781540458939176,-1.9373709211783434,-0.4020444… │ │
│ │                    gene_symbol 9:                                        │ │

```sh
featherplot-py featherplot add-sidecars --help

Usage: featherplot add-sidecars 
[OPTIONS]
--tileset          PATH  Path to the tileset to add sidecars to.
--sidecar          PATH  Path to the new data to add to the tileset.
--key              TEXT  key to use for joining; must exist in both tables
--verbose  -v            Print verbose output.
--help                   Show this message and exit.
```

alternatively you can run the script form wherever you saved it

In [26]:
!python3 add_sidecars.py --tileset {qf_dir}\
                         --sidecar {f_file} --key {d2m.df.index.name};

python3: can't open file '/home/hm3/Desktop/complaint-plotter/add_sidecars.py': [Errno 2] No such file or directory

### 4) update metadata with directory

In [27]:
meta.keys()

dict_keys(['index', 'n_points', 'embedding', 'sidecars', 'columns_metadata', 'tiles_dir'])

In [28]:
# relative path to tiles
meta['tiles_dir'] = qf_dir.replace(outdir, '')
# full path to tiles
meta['full_path'] = collapse_user(qf_dir)

In [29]:
with open(m_file, 'w') as f:
    f.write(yaml.dump(meta))
    
print(f"Write out at {m_file}")

Write out at /home/hm3/Downloads/featherplot/meta.yml

### 5) cleanup